import { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Terms of Service - ResearchScoutAI',
    description: 'Terms and conditions for using ResearchScoutAI.',
};

export default function TermsPage() {
    return (
        <main className="min-h-screen premium-bg grid-pattern text-slate-200 py-12 px-4 sm:px-6 lg:px-8">
            <div className="max-w-3xl mx-auto bg-slate-900/50 backdrop-blur-md rounded-2xl p-8 border border-white/10 shadow-2xl">
                <h1 className="text-3xl font-display font-bold text-white mb-8">Terms of Service</h1>

                <div className="space-y-6 text-sm sm:text-base leading-relaxed">
                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">1. Acceptance of Terms</h2>
                        <p>By accessing and using ResearchScoutAI, you accept and agree to be bound by the terms and provision of this agreement.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">2. Service Description</h2>
                        <p>ResearchScoutAI provides AI-generated research and lead enrichment services. We process public web data to provide insights.</p>
                    </section>

                    <section className="p-4 bg-red-500/10 border border-red-500/20 rounded-lg">
                        <h2 className="text-xl font-semibold text-red-400 mb-3">3. Refund Policy</h2>
                        <p className="font-medium text-white/90">
                            ALL SALES ARE FINAL. Due to the digital nature of our product, once payment is processed and the lead data is unlocked/delivered, no refunds will be issued under any circumstances.
                        </p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">4. Acceptable Use Policy</h2>
                        <p>You agree NOT to use the data provided for:</p>
                        <ul className="list-disc pl-5 space-y-2 mt-2">
                            <li>Sending unsolicited spam emails in violation of CAN-SPAM or GDPR.</li>
                            <li>Harassment or abusive communication.</li>
                            <li>Reselling the raw data to third parties.</li>
                        </ul>
                        <p className="mt-2">ResearchScoutAI reserves the right to terminate accounts found in violation of this policy without refund.</p>
                    </section>

                    <section>
                        <h2 className="text-xl font-semibold text-white mb-3">5. Disclaimer</h2>
                        <p>The insights provided are generated by AI based on public data. We do not guarantee 100% accuracy of the information provided.</p>
                    </section>
                </div>

                <div className="mt-12 pt-8 border-t border-white/10 text-center">
                    <a href="/" className="text-violet-400 hover:text-violet-300 transition-colors">← Back to Dashboard</a>
                </div>
            </div>
        </main>
    );
}
